services:
  app:
    image: ghcr.io/what-s-love/moto-rental:${APP_VERSION:-latest}
    container_name: moto-trip
    restart: unless-stopped
    network_mode: host

    mem_limit: 500m
    mem_reservation: 256m

#    Игнорируются при использовании network_mode
#    ports:
#      - "127.0.0.1:8080:8080"
    volumes:
      - /srv/moto-trip/uploads:/app/data
    env_file:
      - /etc/moto-trip/app.env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"