server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:moto_rental_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    default-schema: public
  # H2 Console (опционально, для отладки)
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:email@example.com}
    password: ${MAIL_PASSWORD:https://myaccount.google.com/apppasswords}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    liquibase: INFO
    org.hibernate.SQL: WARN
    ge.tsepesh.motorental: INFO
