server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:file:./data/moto_rental_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Пересоздаёт схему при старте
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    default-schema: public
  
  # H2 Console (опционально, для отладки)
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    liquibase: INFO
    org.hibernate.SQL: WARN
    ge.tsepesh.motorental: INFO
